
markdown: kramdown

highlighter: rouge
permalink: pretty
url: https://morvanzhou.github.io
baseurl:

exclude: ['README.md']


# collection and their defaults

collections:
  tutorial_page_contents:
    output: false
  contents:
    output: true
    permalink: /:path/



defaults:
  - scope:
      path: "_contents/pages/tutorial-home-page"
    values:
      content-for: tutorials

  - scope:
      path: "_contents/pages/module-descriptions/python-basic"
    values:
      content-for: python-basic

  - scope:
      path: "_contents/pages/module-descriptions/data-manipulation"
    values:
      content-for: data-manipulation

  - scope:
      path: "_contents/pages/module-descriptions/machine-learning"
    values:
      content-for: machine-learning

  - scope:
      path: "_contents/pages/module-descriptions/others"
    values:
      content-for: others

  - scope:
      path: "_contents/tutorials"
    values:
      editor: 莫烦
      author: 莫烦
      author-link: "#"
      autoplay: true
      published: true
      comments: true
      sort-date: true
      keywords: 教学, 教程, 学习

  ### start of tutorials ###

  - scope:
      path: "_contents/tutorials/machine-learning/ML-intro"
    values:
      layout: tutorial-post
      tut-title: 有趣的机器学习
      tut-permalink: /tutorials/machine-learning/ML-intro/
      category: ML-intro
      keywords: 机器学习, 简介, 动画

  - scope:
      path: "_contents/tutorials/machine-learning/reinforcement-learning"
    values:
      layout: tutorial-post
      tut-title: 强化学习 Reinforcement Learning
      tut-permalink: /tutorials/machine-learning/reinforcement-learning/
      category: reinforcement-learning
      keywords: reinforcement learning, 强化学习, tensorflow

  - scope:
      path: "_contents/tutorials/machine-learning/evolutionary-algorithm"
    values:
      layout: tutorial-post
      tut-title: 进化算法
      tut-permalink: /tutorials/machine-learning/evolutionary-algorithm/
      category: evolutionary-algorithm
      keywords: evolutionary algorithm, 进化算法, 遗传算法, genetic algorithm, neuro evalution

  - scope:
      path: "_contents/tutorials/machine-learning/keras"
    values:
      layout: tutorial-post
      tut-title: Keras
      tut-permalink: /tutorials/machine-learning/keras/
      category: keras
      keywords: keras, 神经网络, tensorflow, theano

  - scope:
      path: "_contents/tutorials/machine-learning/torch"
    values:
      layout: tutorial-post
      tut-title: PyTorch
      tut-permalink: /tutorials/machine-learning/torch/
      category: torch
      keywords: Torch, pytorch, 神经网络

  - scope:
      path: "_contents/tutorials/machine-learning/sklearn"
    values:
      layout: tutorial-post
      tut-title: Sklearn
      tut-permalink: /tutorials/machine-learning/sklearn/
      category: sklearn
      keywords: sklearn, scikit-learn, 机器学习


  - scope:
      path: "_contents/tutorials/machine-learning/tensorflow"
    values:
      layout: tutorial-post
      tut-title: Tensorflow
      tut-permalink: /tutorials/machine-learning/tensorflow/
      category: tensorflow
      keywords: tensorflow, tensorboard, 机器学习, 神经网络

  - scope:
      path: "_contents/tutorials/machine-learning/theano"
    values:
      layout: tutorial-post
      tut-title: Theano
      tut-permalink: /tutorials/machine-learning/theano/
      category: theano
      keywords: theano, 机器学习, 神经网络

  - scope:
      path: "_contents/tutorials/data-manipulation/np-pd"
    values:
      layout: tutorial-post
      tut-title: Numpy & Pandas
      tut-permalink: /tutorials/data-manipulation/np-pd/
      category: np-pd
      keywords: numpy, pandas, 数据, 处理

  - scope:
      path: "_contents/tutorials/data-manipulation/plt"
    values:
      layout: tutorial-post
      tut-title: Matplotlib
      tut-permalink: /tutorials/data-manipulation/plt/
      category: plt
      keywords: matplotlib, plt, 数据可视化

  - scope:
      path: "_contents/tutorials/python-basic/basic"
    values:
      layout: tutorial-post
      tut-title: Python 基础
      tut-permalink: /tutorials/python-basic/basic/
      category: Python 基础
      keywords: python, 基础

  - scope:
      path: "_contents/tutorials/python-basic/multiprocessing"
    values:
      layout: tutorial-post
      tut-title: 多进程 Multiprocessing
      tut-permalink: /tutorials/python-basic/multiprocessing/
      category: multiprocessing
      keywords: python, 基础, 多进程, multiprocessing

  - scope:
      path: "_contents/tutorials/python-basic/threading"
    values:
      layout: tutorial-post
      tut-title: 多线程 Threading
      tut-permalink: /tutorials/python-basic/threading/
      category: threading
      keywords: python, 基础, 多线程, threading


  - scope:
      path: "_contents/tutorials/python-basic/tkinter"
    values:
      layout: tutorial-post
      tut-title: 窗口 Tkinter
      tut-permalink: /tutorials/python-basic/tkinter/
      category: tkinter
      keywords: python, 基础, GUI, 窗口, tkinter, tk

  - scope:
      path: "_contents/tutorials/python-basic/basic"
    values:
      layout: tutorial-post
      tut-title: Python 基础
      tut-permalink: /tutorials/python-basic/basic/
      category: basic
      keywords: python, 基础

  - scope:
      path: "_contents/tutorials/others/git"
    values:
      layout: tutorial-post
      tut-title: Git 版本管理
      tut-permalink: /tutorials/others/git/
      category: git
      keywords: 其他, git, VCS
